Repository sderacy/gooncard, pull requests merged in 2022-11, with the labels that each got.

#69 Implements a fixed but content-aware footer
  public/common.css
  views/aboutus/index.ejs
  views/account/profile/index.ejs
  views/account/settings/index.ejs
  views/account/signup/index.ejs
  views/home/index.ejs
  views/partials/footer.ejs
  views/partials/navbar.ejs
Labels: frontend

#76 Add accounts interface
  db/seed.js
  db/userAccounts.js
  db/users.js
  routes/login.js
  views/home/index.ejs
Labels: backend

#83 Add accounts endpoints
  db/userAccounts.js
  routes/profile.js
  views/account/profile/index.ejs
  views/account/profile/main.js
  views/account/profile/style.css
Labels: frontend, backend

#87 Displays user accounts on home page, QR code generates with toggled accounts.
  views/account/profile/main.js
  views/home/main.js
Labels: frontend, backend

#105 Fixes registration bug by getting the user's id on registration.
  db/users.js
Labels: backend, bug

#89 Implement settings functionality
  db/defaultSettings.json
  routes/profile.js
  views/aboutus/index.ejs
  views/account/login/index.ejs
  views/account/profile/index.ejs
  views/account/profile/main.js
  views/account/settings/index.ejs
  views/account/settings/main.js
  views/account/signup/index.ejs
  views/home/index.ejs
  views/home/main.js
  views/partials/header.ejs
Labels: frontend, backend

#101 Not found page
  routes/displaycard.js
  routes/notfound.js
  server.js
  views/displaycard/index.ejs
  views/displaycard/main.js
  views/displaycard/style.css
  views/notfound/index.ejs
  views/notfound/main.js
  views/notfound/style.css
  views/partials/header.ejs
Labels: frontend

#109 Add font settings
  views/aboutus/main.js
  views/account/profile/main.js
  views/account/settings/main.js
  views/home/main.js
  views/partials/header.ejs
Labels: frontend

#108 Fix dropdown
  views/partials/footer.ejs
  views/partials/header.ejs
  views/partials/navbar.ejs
Labels: frontend, bug

#120 Add settings buttons
  db/defaultSettings.json
  routes/settings.js
  views/account/settings/index.ejs
  views/account/settings/main.js
Labels: frontend, backend

#121 Creation of card_entries table and functions
  db/cardEntry.js
  db/schema.sql
  db/seed.js
Labels: backend

#102 Created ReadMe branch and added general information
  README.md
Labels: documentation

#122 No account text
  views/account/profile/index.ejs
  views/account/profile/main.js
  views/home/index.ejs
  views/home/main.js
  views/home/style.css
Labels: frontend, backend

#123 Add qrcode endpoint
  package.json
  routes/displaycard.js
  routes/home.js
  server.js
  views/displaycard/index.ejs
  views/home/index.ejs
  views/home/main.js
Labels: frontend, backend

#128 Fix mobile bug
  routes/home.js
  views/aboutus/main.js
  views/account/profile/main.js
  views/account/settings/main.js
  views/displaycard/index.ejs
  views/home/main.js
Labels: frontend, backend, bug

#125 READMe Update
  README.md
Labels: documentation

#132 Removed value from homepage
  views/home/main.js
Labels: frontend

#131 Add theme settings
  db/defaultSettings.json
  public/common.css
  views/aboutus/index.ejs
  views/aboutus/main.js
  views/account/login/index.ejs
  views/account/profile/index.ejs
  views/account/profile/main.js
  views/account/profile/style.css
  views/account/settings/index.ejs
  views/account/settings/main.js
  views/account/signup/index.ejs
  views/displaycard/index.ejs
  views/home/index.ejs
  views/home/main.js
  views/home/style.css
  views/notfound/index.ejs
  views/partials/footer.ejs
  views/partials/navbar.ejs
Labels: frontend

#135 Fix theme flashing
  views/aboutus/index.ejs
  views/aboutus/main.js
  views/account/profile/index.ejs
  views/account/profile/main.js
  views/account/settings/index.ejs
  views/account/settings/main.js
  views/displaycard/index.ejs
  views/home/index.ejs
  views/home/main.js
  views/notfound/index.ejs
  views/partials/defaultSettings.ejs
  views/partials/setSettingsForm.ejs
Labels: frontend, backend, bug

#130 Made a tiny change that fixes a bug for the buttons on the home page (casual, professional, all).
  views/home/index.ejs
  views/home/main.js
Labels: frontend, bug

#136 Implement contrast for settings page
  public/common.css
  views/aboutus/index.ejs
  views/account/profile/index.ejs
  views/account/profile/style.css
  views/account/settings/index.ejs
  views/home/index.ejs
  views/home/main.js
  views/partials/defaultSettings.ejs
  views/partials/footer.ejs
  views/partials/navbar.ejs
  views/partials/setSettingsForm.ejs
Labels: frontend

#140 Fix displaycard
  views/displaycard/index.ejs
Labels: frontend, backend, bug

#142 Change font families
  views/partials/setSettingsForm.ejs
Labels: frontend

#143 Added a11y features, buttons, and updated radio button
  public/common.css
  views/account/profile/index.ejs
  views/account/profile/main.js
  views/account/settings/index.ejs
  views/account/settings/style.css
  views/home/index.ejs
  views/home/main.js
  views/home/style.css
  views/partials/defaultSettings.ejs
  views/partials/footer.ejs
  views/partials/navbar.ejs
  views/partials/setSettingsForm.ejs
Labels: frontend

#155 Adds the 'start-vm' and 'cleanStart-vm' script variations for the cluster VM.
  README.md
  package.json
  server.js
Labels: backend, bug

#149 Adds changes necessary for cascading deletions.
  db/schema.sql
  db/userAccounts.js
Labels: backend, bug

#151 Adds dynamic displaycard generation.
  db/cardEntry.js
  routes/displaycard.js
  views/displaycard/index.ejs
  views/displaycard/main.js
  views/notfound/index.ejs
  views/partials/defaultSettings.ejs
Labels: backend

#144 Implemented the speech recognition on the homepage
  views/account/profile/index.ejs
  views/account/settings/index.ejs
  views/displaycard/index.ejs
  views/home/index.ejs
  views/home/main.js
  views/home/style.css
Labels: frontend

#158 Commenting Code and Front End Changes
  public/common.css
  views/aboutus/index.ejs
  views/aboutus/main.js
  views/aboutus/style.css
  views/account/profile/index.ejs
  views/account/profile/main.js
  views/account/profile/style.css
  views/account/settings/style.css
  views/displaycard/main.js
  views/displaycard/style.css
  views/home/index.ejs
  views/home/main.js
  views/home/style.css
  views/notfound/style.css
  views/partials/defaultSettings.ejs
  views/partials/setSettingsForm.ejs
Labels: documentation, frontend

#164 Fixes light mode, high contrast setting for real.
  views/partials/setSettingsForm.ejs
Labels: frontend, backend, bug

#161 Help feature on interactive pages
  README.md
  public/common.css
  views/account/profile/index.ejs
  views/account/profile/style.css
  views/account/settings/index.ejs
  views/home/index.ejs
  views/partials/modal.ejs
Labels: enhancement, frontend
