Repository sderacy/gooncard, pull requests merged in 2022-12, with the labels that each got.

#169 Added more about accessibility in the readme
  README.md
Labels: documentation, frontend, backend

#160 Finish up ReadMe Documentation
  README.md
Labels: documentation, frontend, backend

#168 Fixes #167 by underlining links in black on the display card page and…
  views/displaycard/main.js
Labels: frontend

#173 Adds VM access instructions to readme.
  README.md
Labels: documentation

#174 Update README.md
  README.md
Labels: documentation
